((lambda ()
    (set! global-environment
       ((lambda (p)
           (lambda args (if (not (null? args)) (set! p (car args)) p)))
        '()))
    'global-environment))
((lambda () (set! expand #f) 'expand))
((lambda () (set! unwrap-syntax #f) 'unwrap-syntax))
((lambda () (set! identifier? #f) 'identifier?))
((lambda () (set! free-identifier=? #f) 'free-identifier=?))
((lambda ()
    (set! bound-identifier=? #f)
    'bound-identifier=?))
((lambda ()
    (set! identifier->symbol #f)
    'identifier->symbol))
((lambda ()
    (set! generate-identifier #f)
    'generate-identifier))
((lambda () (set! syntax-error #f) 'syntax-error))
((lambda ()
    (set! construct-identifier #f)
    'construct-identifier))
((lambda ()
    (set! boot-install-global-transformer #f)
    'boot-install-global-transformer))
((lambda ()
    (set! boot-make-global-identifier #f)
    'boot-make-global-identifier))
